_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 49
                - 51
                - 55
            "2":
                - 49
                - 51
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
